"""Auto-fix service for creating tasks from failures."""

from typing import Any

from agent_pump.integrations.failure_parser import FailureInfo
from agent_pump.models.project import Project
from agent_pump.models.roadmap import RoadmapStatus
from agent_pump.services.roadmap_service import RoadmapService


class AutoFixService:
    """Service to create auto-fix tasks."""

    def create_fix_task(
        self,
        project: Project,
        failure_info: FailureInfo,
        run_id: int,
        retry_count: int,
    ) -> None:
        """Create a roadmap task for the failure."""
        roadmap_service = RoadmapService(project)

        # Construct detailed description
        errors_fmt = self._format_errors(failure_info.errors)

        description = f"""
## CI Failure Details

**Errors Found:**
{errors_fmt}

**Suggested Approach:**
{failure_info.suggested_fix}

**Raw Log (last 500 chars):**
```
{failure_info.raw_log[-500:]}
```

---
*Auto-generated by Agent Pump CI Watcher*
"""

        roadmap_service.add_item(
            title=f"🔧 Fix CI Failure: {failure_info.suggested_fix}",
            description=description,
            priority="High",
            status=RoadmapStatus.NOT_STARTED,
            section="current",
            position="top",
            metadata={
                "auto_generated": True,
                "ci_run_id": run_id,
                "retry_count": retry_count,
            },
        )

    def _format_errors(self, errors: list[dict[str, Any]]) -> str:
        """Format errors as a markdown list."""
        if not errors:
            return "No specific error patterns matched."

        lines = []
        for err in errors[:10]:  # Limit to 10 errors to avoid huge description
            lines.append(f"- **{err['type']}**: `{err['details']}`")

        if len(errors) > 10:
            lines.append(f"- ... and {len(errors) - 10} more errors")

        return "\n".join(lines)
